/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a phone or watch device and mint a session token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceEnrollRequest"];
                };
            };
            responses: {
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a device session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    device_id: components["parameters"]["DeviceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a 6-digit pairing code so a companion device can join the same user
         * @description Authenticated as the originating phone. The phone forwards the returned
         *     `code` to the companion (e.g. via WatchConnectivity), which then calls
         *     `POST /v1/auth/devices` with `pairing_code` set. Codes expire after 5
         *     minutes and are single-use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pairing"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wrapping-keys/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current ECIES wrapping public key (X25519)
         * @description Returned to authenticated clients before they enroll a provider account.
         *     The phone uses this key to wrap the provider API key with
         *     `X25519-HKDF-SHA256-AES256GCM`. Wire format of the resulting
         *     `wrapped_key` is `[32-byte ephemeral pubkey][12-byte iv][16-byte tag][ciphertext]`,
         *     base64-encoded.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WrappingKey"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provider accounts the caller has enrolled */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
            };
        };
        put?: never;
        /** Enroll a provider account (Anthropic or OpenAI) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account_id}/limits": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Set per-account caps used by the threshold evaluator */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountLimits"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force an immediate poll of this account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refresh enqueued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshAck"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch-friendly snapshot — used by complications and tiles */
        get: {
            parameters: {
                query?: {
                    window?: "hour" | "day" | "week" | "month" | "reset_window";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time-bucketed series for the dashboard */
        get: {
            parameters: {
                query: {
                    account_id?: string;
                    from: string;
                    to: string;
                    bucket?: "hour" | "day";
                    group_by?: "model" | "provider" | "none";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageSeries"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertThreshold"][];
                    };
                };
            };
        };
        /** Replace the caller's alert thresholds */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlertThresholdInput"][];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertThreshold"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Register or update the APNs / FCM token for the caller's device */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PushTokenInput"];
                };
            };
            responses: {
                /** @description Stored */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Forget the push token for the caller's device */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desktop agent uploads incremental Claude Code / Codex log counters
         * @description Used by the Tauri desktop agent to deliver locally-parsed counters that
         *     can't be obtained from a public provider API (e.g. Claude Code Pro/Max
         *     5-hour reset window). Payload is restricted to numeric counters — never
         *     prompt or completion content.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgentIngest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** Format: date-time */
            time: string;
        };
        DeviceEnrollRequest: {
            /** @enum {string} */
            platform: "ios" | "android" | "watchos" | "wearos" | "desktop";
            /** @description Base64 X25519 public key used for end-to-end key wrapping */
            public_key: string;
            /**
             * @description Optional. When present, the new device joins the user that issued
             *     the pairing code via `POST /v1/auth/pairings`. When absent, a new
             *     user is created.
             */
            pairing_code?: string;
            device_name?: string;
        };
        Pairing: {
            code: string;
            /** Format: date-time */
            expires_at: string;
        };
        Session: {
            /** Format: uuid */
            device_id: string;
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        Provider: "anthropic" | "openai";
        WrappingKey: {
            kid: string;
            /** @description Base64 raw 32-byte X25519 public key */
            public_key: string;
            /** @enum {string} */
            alg: "X25519-HKDF-SHA256-AES256GCM";
        };
        AccountCreate: {
            provider: components["schemas"]["Provider"];
            label: string;
            /**
             * @description Base64 ECIES envelope of the provider API key. Layout:
             *     `[32-byte ephemeral pubkey][12-byte iv][16-byte tag][ciphertext]`.
             *     HKDF salt is the recipient public key, info is `pulsewatch v1`.
             */
            wrapped_key: string;
            /** @description Must equal the kid returned by GET /v1/wrapping-keys/current */
            kid: string;
            /** @description Required for OpenAI; ignored for Anthropic */
            org_id?: string;
        };
        AccountLimits: {
            daily_cap_usd?: number | null;
            monthly_cap_usd?: number | null;
            daily_cap_tokens?: number | null;
            /** @description For Claude Code Pro/Max — token cap inside `reset_window_seconds`. */
            reset_window_cap_tokens?: number | null;
            /**
             * @description Length of the rolling reset window. Defaults to 5 hours.
             * @default 18000
             */
            reset_window_seconds: number;
        };
        Account: {
            /** Format: uuid */
            id: string;
            provider: components["schemas"]["Provider"];
            label: string;
            org_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_polled_at?: string | null;
            /** @enum {string} */
            status: "pending" | "active" | "error";
            error_message?: string | null;
        };
        RefreshAck: {
            /** Format: uuid */
            account_id: string;
            /** Format: date-time */
            enqueued_at: string;
        };
        UsageSummary: {
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            window: "hour" | "day" | "week" | "month" | "reset_window";
            providers: components["schemas"]["ProviderSummary"][];
        };
        ProviderSummary: {
            provider: components["schemas"]["Provider"];
            label?: string;
            used: number;
            limit: number | null;
            /** @enum {string} */
            unit: "usd" | "tokens" | "requests";
            percent: number | null;
            /** Format: date-time */
            resets_at?: string | null;
            /** Format: date-time */
            projected_exhaustion_at?: string | null;
        };
        UsageSeries: {
            /** @enum {string} */
            bucket: "hour" | "day";
            points: components["schemas"]["UsagePoint"][];
        };
        UsagePoint: {
            /** Format: date-time */
            t: string;
            value: number;
            /** @description model id or provider id when group_by != none */
            group?: string;
            /** @enum {string} */
            unit?: "usd" | "tokens" | "requests";
        };
        AlertThresholdInput: {
            /** @enum {string} */
            scope: "provider_day" | "provider_month" | "claude_code_reset_window";
            provider?: components["schemas"]["Provider"];
            percent: number;
            /** @default true */
            haptic: boolean;
        };
        AlertThreshold: components["schemas"]["AlertThresholdInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_fired_at?: string | null;
        };
        PushTokenInput: {
            /** @enum {string} */
            platform: "ios" | "watchos" | "android" | "wearos";
            /** @description Hex-encoded APNs device token. Provide this and/or fcm_token. */
            apns_token?: string;
            /** @enum {string} */
            apns_environment?: "sandbox" | "production";
            fcm_token?: string;
        };
        AgentIngest: {
            /** Format: uuid */
            agent_id: string;
            samples: {
                /** Format: date-time */
                t: string;
                /** @enum {string} */
                source: "claude_code" | "codex_cli";
                model?: string;
                input_tokens: number;
                output_tokens: number;
                cache_read_tokens?: number;
                cache_write_tokens?: number;
                cost_usd?: number;
            }[];
        };
    };
    responses: never;
    parameters: {
        AccountId: string;
        DeviceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
